name: 'my first container file'
description: 'A Cloud Guru'
author: 'Rob Light'
inputs:
  myinput:
    description: 'greeting to use'
    required: true
    default: 'Awsome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
